export const CURRENCY_PAIRS_MAP = {
  'eur-usd': { value: 'eur-usd', label: 'EUR/USD' },
  'eur-jpy': { value: 'eur-jpy', label: 'EUR/JPY' },
  'gbp-jpy': { value: 'gbp-jpy', label: 'GBP/JPY' },
  'us-500-otc': { value: 'us-500-otc', label: 'US 500 (OTC)' },
  'gbp-usd': { value: 'gbp-usd', label: 'GBP/USD' },
  'aud-nzd': { value: 'aud-nzd', label: 'AUD/NZD' },
  'us-100-otc': { value: 'us-100-otc', label: 'US 100 (OTC)' },
  'usd-cad': { value: 'usd-cad', label: 'USD/CAD' },
  'xau-usd': { value: 'xau-usd', label: 'XAU/USD' },
  'aud-jpy-otc': { value: 'aud-jpy-otc', label: 'AUD/JPY (OTC)' },
  'aud-chf': { value: 'aud-chf', label: 'AUD/CHF' },
  'aud-usd': { value: 'aud-usd', label: 'AUD/USD' },
  'eur-cad-otc': { value: 'eur-cad-otc', label: 'EUR/CAD (OTC)' },
  'aud-usd-otc': { value: 'aud-usd-otc', label: 'AUD/USD (OTC)' },
  'eur-chf': { value: 'eur-chf', label: 'EUR/CHF' },
  'eur-aud': { value: 'eur-aud', label: 'EUR/AUD' },
  'nzd-cad': { value: 'nzd-cad', label: 'NZD/CAD' },
  'aud-chf-otc': { value: 'aud-chf-otc', label: 'AUD/CHF (OTC)' },
  'usd-cad-otc': { value: 'usd-cad-otc', label: 'USD/CAD (OTC)' },
  'btc-usd': { value: 'btc-usd', label: 'BTC/USD' },
  'usd-zar': { value: 'usd-zar', label: 'USD/ZAR' },
  'chf-jpy-otc': { value: 'chf-jpy-otc', label: 'CHF/JPY (OTC)' },
  'usd-sgd': { value: 'usd-sgd', label: 'USD/SGD' },
  'nzd-jpy': { value: 'nzd-jpy', label: 'NZD/JPY' },
  'gbp-nzd': { value: 'gbp-nzd', label: 'GBP/NZD' },
  'gbp-chf': { value: 'gbp-chf', label: 'GBP/CHF' },
  'us-30-otc': { value: 'us-30-otc', label: 'US 30 (OTC)' },
  'cad-chf': { value: 'cad-chf', label: 'CAD/CHF' },
  'usd-try-otc': { value: 'usd-try-otc', label: 'USD/TRY (OTC)' },
  'eur-cad': { value: 'eur-cad', label: 'EUR/CAD' },
  'gbp-aud-otc': { value: 'gbp-aud-otc', label: 'GBP/AUD (OTC)' },
  'eur-nzd-otc': { value: 'eur-nzd-otc', label: 'EUR/NZD (OTC)' },
  'eur-nzd': { value: 'eur-nzd', label: 'EUR/NZD' },
  'usd-hkd': { value: 'usd-hkd', label: 'USD/HKD' },
  'gbp-aud': { value: 'gbp-aud', label: 'GBP/AUD' },
  'gbp-cad': { value: 'gbp-cad', label: 'GBP/CAD' },
  'cad-jpy-otc': { value: 'cad-jpy-otc', label: 'CAD/JPY (OTC)' },
  'eur-chf-otc': { value: 'eur-chf-otc', label: 'EUR/CHF (OTC)' },
  'gbp-cad-otc': { value: 'gbp-cad-otc', label: 'GBP/CAD (OTC)' },
  'aud-nzd-otc': { value: 'aud-nzd-otc', label: 'AUD/NZD (OTC)' },
  'eur-aud-otc': { value: 'eur-aud-otc', label: 'EUR/AUD (OTC)' },
  'nzd-jpy-otc': { value: 'nzd-jpy-otc', label: 'NZD/JPY (OTC)' },
  'cad-chf-otc': { value: 'cad-chf-otc', label: 'CAD/CHF (OTC)' },
  'gbp-nzd-otc': { value: 'gbp-nzd-otc', label: 'GBP/NZD (OTC)' },
  'nzd-cad-otc': { value: 'nzd-cad-otc', label: 'NZD/CAD (OTC)' },
  'usd-sek-otc': { value: 'usd-sek-otc', label: 'USD/SEK (OTC)' },
  'usd-nok-otc': { value: 'usd-nok-otc', label: 'USD/NOK (OTC)' },
  'us-100': { value: 'us-100', label: 'US 100' },
  'usd-pln-otc': { value: 'usd-pln-otc', label: 'USD/PLN (OTC)' },
  'us-30': { value: 'us-30', label: 'US 30' },
  'us-500': { value: 'us-500', label: 'US 500' },
  'eur-gbp': { value: 'eur-gbp', label: 'EUR/GBP' },
  'aud-cad': { value: 'aud-cad', label: 'AUD/CAD' },
  'aud-jpy': { value: 'aud-jpy', label: 'AUD/JPY' },
  'eur-jpy-otc': { value: 'eur-jpy-otc', label: 'EUR/JPY (OTC)' }
};

export const CURRENCY_PAIRS_VALUES = [
  { value: 'eur-usd', label: 'EUR/USD' },
  { value: 'eur-jpy', label: 'EUR/JPY' },
  { value: 'gbp-jpy', label: 'GBP/JPY' },
  { value: 'us-500-otc', label: 'US 500 (OTC)' },
  { value: 'gbp-usd', label: 'GBP/USD' },
  { value: 'aud-nzd', label: 'AUD/NZD' },
  { value: 'us-100-otc', label: 'US 100 (OTC)' },
  { value: 'usd-cad', label: 'USD/CAD' },
  { value: 'xau-usd', label: 'XAU/USD' },
  { value: 'aud-jpy-otc', label: 'AUD/JPY (OTC)' },
  { value: 'aud-chf', label: 'AUD/CHF' },
  { value: 'aud-usd', label: 'AUD/USD' },
  { value: 'eur-cad-otc', label: 'EUR/CAD (OTC)' },
  { value: 'aud-usd-otc', label: 'AUD/USD (OTC)' },
  { value: 'eur-chf', label: 'EUR/CHF' },
  { value: 'eur-aud', label: 'EUR/AUD' },
  { value: 'nzd-cad', label: 'NZD/CAD' },
  { value: 'aud-chf-otc', label: 'AUD/CHF (OTC)' },
  { value: 'usd-cad-otc', label: 'USD/CAD (OTC)' },
  { value: 'btc-usd', label: 'BTC/USD' },
  { value: 'eth-usd', label: 'ETH/USD' },
  { value: 'usd-zar', label: 'USD/ZAR' },
  { value: 'chf-jpy-otc', label: 'CHF/JPY (OTC)' },
  { value: 'usd-sgd', label: 'USD/SGD' },
  { value: 'nzd-jpy', label: 'NZD/JPY' },
  { value: 'gbp-nzd', label: 'GBP/NZD' },
  { value: 'gbp-chf', label: 'GBP/CHF' },
  { value: 'us-30-otc', label: 'US 30 (OTC)' },
  { value: 'cad-chf', label: 'CAD/CHF' },
  { value: 'usd-try-otc', label: 'USD/TRY (OTC)' },
  { value: 'eur-cad', label: 'EUR/CAD' },
  { value: 'gbp-aud-otc', label: 'GBP/AUD (OTC)' },
  { value: 'eur-nzd-otc', label: 'EUR/NZD (OTC)' },
  { value: 'eur-nzd', label: 'EUR/NZD' },
  { value: 'usd-hkd', label: 'USD/HKD' },
  { value: 'gbp-aud', label: 'GBP/AUD' },
  { value: 'gbp-cad', label: 'GBP/CAD' },
  { value: 'cad-jpy-otc', label: 'CAD/JPY (OTC)' },
  { value: 'eur-chf-otc', label: 'EUR/CHF (OTC)' },
  { value: 'gbp-cad-otc', label: 'GBP/CAD (OTC)' },
  { value: 'aud-nzd-otc', label: 'AUD/NZD (OTC)' },
  { value: 'eur-aud-otc', label: 'EUR/AUD (OTC)' },
  { value: 'nzd-jpy-otc', label: 'NZD/JPY (OTC)' },
  { value: 'cad-chf-otc', label: 'CAD/CHF (OTC)' },
  { value: 'gbp-nzd-otc', label: 'GBP/NZD (OTC)' },
  { value: 'nzd-cad-otc', label: 'NZD/CAD (OTC)' },
  { value: 'usd-sek-otc', label: 'USD/SEK (OTC)' },
  { value: 'usd-nok-otc', label: 'USD/NOK (OTC)' },
  { value: 'us-100', label: 'US 100' },
  { value: 'usd-pln-otc', label: 'USD/PLN (OTC)' },
  { value: 'us-30', label: 'US 30' },
  { value: 'us-500', label: 'US 500' },
  { value: 'eur-gbp', label: 'EUR/GBP' },
  { value: 'aud-cad', label: 'AUD/CAD' },
  { value: 'aud-jpy', label: 'AUD/JPY' },
  { value: 'eur-jpy-otc', label: 'EUR/JPY (OTC)' }
];

export const EXPIRATION_TIMES = [
  { value: 5, label: '5 seg' },
  { value: 10, label: '10 seg' },
  { value: 15, label: '15 seg' },
  { value: 30, label: '30 seg' },
  { value: 45, label: '45 seg' },
  { value: 60, label: '1 min' },
  { value: 120, label: '2 min' },
  { value: 180, label: '3 min' },
  { value: 300, label: '5 min' }
];

export const PATTERNS = {
  put: 'Venda',
  call: 'Compra'
};
